spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/blog_tintin?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: info
    com.tintin: debug
  file:
    name: log/blog-dev.log
